# -*- coding: utf-8 -*-
"""Build a GymSupplementShop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1cVc2H883JPRwbCV70X-JfmhtCfqsO1
"""

StoreProducts_INR_Prices= {"Pre-Workout": 1500,"BCAAEnergy": 1200,"WheyProtien": 2700, "WheyProtien Isolate": 3400,"Creatine": 800}

print("""Welcome to MyGym-Supplement Store", "Let's order your fav supplement and get your desired body transformation!
"Pre-Workout": 1500,"BCAAEnergy": 1200,"Whey": 2700, "WheyProtien Isolate": 3400,"Creatine": 800 """)

Total_Price=0

item1= input("Enter the item name: ")
if item1 in StoreProducts_INR_Prices:
  Total_Price += StoreProducts_INR_Prices[item1]
  print(f"You Ordered {item1}. Your Total order is  RS.{Total_Price}.")

else:
  print("This item is not in our Shop, Please order something from the StoreProducts_INR_Prices! ")

another_item= input("Do you want to order another item? (yes/no): ")

if another_item.lower() == "yes":
  item2= input("Enter the Second item name you want to order: ")
  if item2 in StoreProducts_INR_Prices:
    Total_Price += StoreProducts_INR_Prices[item2]
    print(f"You Ordered {item2}. Your Total order is  RS.{Total_Price}.")
  else:
    print("This item is not in our Shop, Please order something from the StoreProducts_INR_Prices! ")

print(f"You Total amount is Rs.{Total_Price}. Thanking You! Keep Lifting Hard in Gym!")

